uptime-kuma/Dockerfile
uptime-kuma/build.yaml

Upgrades add-on base image to 12.2.1

⬆️ Upgrades add-on base image to 12.2.1

---

uptime-kuma/Dockerfile

Upgrades Uptime Kuma to 1.17.1
<https://github.com/hassio-addons/addon-bitwarden/releases/tag/v0.17.1>
<https://github.com/hassio-addons/addon-bitwarden/releases/tag/v0.17.0>

⬆️ Upgrades Uptime Kuma to 1.17.1

---

uptime-kuma/Dockerfile
uptime-kuma/build.yaml

⬆️ Upgrades add-on base image to 12.2.2

---

uptime-kuma/Dockerfile
uptime-kuma/build.yaml

⬆️ Upgrades add-on base image to 12.2.4

---

uptime-kuma/Dockerfile

<https://github.com/louislam/uptime-kuma/releases/tag/1.18.0>

⬆️ Upgrades Uptime Kuma to 1.18.0

---

uptime-kuma/Dockerfile

⬆️ Upgrades nodejs to 16.17.1-r0

---

uptime-kuma/Dockerfile

- https://github.com/louislam/uptime-kuma/releases/tag/1.18.4
- https://github.com/louislam/uptime-kuma/releases/tag/1.18.3
- https://github.com/louislam/uptime-kuma/releases/tag/1.18.2
- https://github.com/louislam/uptime-kuma/releases/tag/1.18.1

⬆️ Upgrades Uptime Kuma to 1.18.4

---

uptime-kuma/Dockerfile

Update packaged version of Uptime Kuma to the latest version (1.18.5)
* https://github.com/louislam/uptime-kuma/releases/tag/1.18.5

⬆️ Upgrades Uptime Kuma to 1.18.5

---

uptime-kuma/Dockerfile
uptime-kuma/build.yaml

⬆️ Upgrades add-on base image to 12.2.6

---

uptime-kuma/Dockerfile
uptime-kuma/build.yaml

⬆️ Upgrades add-on base image to 12.2.7

---

uptime-kuma/Dockerfile
uptime-kuma/build.yaml

Upgrades the base image to the latest, based on Alpine Linux 3.17, bumps NodeJS to 18

⬆️ Upgrades add-on base image to 13.0.0

---

uptime-kuma/requirements.txt

Adds an Apprise dependency needed for enabling MQTT notifications
fixes #28

:ambulance: Fix MQTT notifications

---

uptime-kuma/Dockerfile

- https://github.com/louislam/uptime-kuma/releases/tag/1.19.2
- https://github.com/louislam/uptime-kuma/releases/tag/1.19.1
- https://github.com/louislam/uptime-kuma/releases/tag/1.19.0

⬆️ Upgrades Uptime Kuma to 1.19.2

---

LICENSE.md
README.md
uptime-kuma/.README.j2
uptime-kuma/DOCS.md

:fireworks: Updates maintenance/license year to 2023

---

uptime-kuma/Dockerfile

https://github.com/louislam/uptime-kuma/releases/tag/1.19.3

⬆️ Upgrades Uptime Kuma to 1.19.3

---

uptime-kuma/Dockerfile

Do not omit optional dependencies from installation.

:ambulance: Do no omit optional dependencies

---

uptime-kuma/Dockerfile
uptime-kuma/build.yaml

⬆️ Upgrades add-on base image to 13.1.0

---

uptime-kuma/Dockerfile

- https://github.com/louislam/uptime-kuma/releases/tag/1.19.4
- https://github.com/louislam/uptime-kuma/releases/tag/1.19.5

⬆️ Upgrades Uptime Kuma to 1.19.5

---

uptime-kuma/Dockerfile

https://github.com/louislam/uptime-kuma/releases/tag/1.19.6

⬆️ Upgrades Uptime Kuma to 1.19.6

---

uptime-kuma/Dockerfile
uptime-kuma/build.yaml

⬆️ Upgrades add-on base image to 13.1.1

---

uptime-kuma/Dockerfile
uptime-kuma/build.yaml

⬆️ Upgrades add-on base image to 13.1.3

---

uptime-kuma/Dockerfile

https://github.com/louislam/uptime-kuma/releases/tag/1.20.2
https://github.com/louislam/uptime-kuma/releases/tag/1.20.1
https://github.com/louislam/uptime-kuma/releases/tag/1.20.0

⬆️ Upgrades Uptime Kuma to 1.20.1

---

uptime-kuma/DOCS.md

> (Describe the changes and rationale behind them)
Fixes a broken URL in the documentation.
> ([Github link][autolink-references] to related issues or pull requests)
[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

Fix broken URL

---

README.md
uptime-kuma/build.yaml
uptime-kuma/config.yaml

Drop support for armhf & i386

---

LICENSE.md
README.md
uptime-kuma/.README.j2
uptime-kuma/DOCS.md

:fireworks: Updates maintenance/license year to 2024

---

LICENSE.md
README.md
uptime-kuma/.README.j2
uptime-kuma/DOCS.md

:fireworks: Updates maintenance/license year to 2025
